# action.yml

runs:
  using: 'docker'
  image: 'docker://typoci/spellcheck-action'
  # When I want to check changes to my Dockerfile, I uncomment the following line:
  # image: 'Dockerfile'
version: '3'
services:
  kali:
    build: .
    cap_add:
      - NET_ADMIN
    stdin_open: true
    tty: true
    ports:
      - "22:22"
